library basic_types

interface Test {
    test_int: (value: int) -> int,
    test_bool: (value: bool) -> bool,
    test_float: (value: float) -> float,
    test_string: (value: string) -> string,
    test_none: (value: none) -> none,
    test_bytes: (value: bytes) -> bytes,
    test_uuid: (value: uuid) -> uuid,
    test_static: static (value: int) -> int,
}

interface TetSt {
    test_int: static (value: int) -> int,
}