name: idl_internal
version: 0.1.3-2.12.0-0
description: idl support for dart
homepage: https://github.com/adrianos42/native_idl_dart

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  ffi: ^0.2.0-nullsafety.1
  quiver: ^3.0.0-nullsafety.3