[package]
name = "idl_rust_gen"
version = "0.1.0"
authors = ["Adriano Souza <adriano.souza113@gmail.com>"]
edition = "2018"

[[bin]]
name = "idl_rust_gen"
path = "src/bin/main.rs"

[dependencies]
clap = "2.33"
native_idl = { path = "../../idl" }
dashmap = "3.11.10"
futures = "0.3.5"
tokio = { version = "0.2", features = ["full"] }
tower-lsp = "0.13.1"
regex = "1.0"
quote = "1.0"
lazy_static = "1.4.0"
proc-macro2 = { version = "1", default-features = false }