library idl_test

interface Test {
    test_int: (value: int) -> int,
    test_bool: (value: bool) -> bool,
    test_float: (value: float) -> float,
    test_string: (value: string) -> string,
    test_none: (value: none) -> none,
    test_bytes: (value: bytes) -> bytes,
    test_uuid: (value: uuid) -> uuid,
    test_int_array: (value: int[]) -> int[],
    test_point_struct: (value: Point) -> Point,
    test_int_map: (value: map[int, string]) -> map[int, string],
    test_int_int_map: (value: map[int, int]) -> map[int, int],
    test_types: (value: Types) -> Types,
    test_option: (value: option[int]) -> option[int],
    test_none_option: option[int],
    test_result: (value: string) -> result[string, bool],
    test_result_err: result[string, bool],
    test_int_stream: stream[string],
    test_pair: (value: pair[string, int]) -> pair[string, int],
    test_names: (value: Names) -> Names,
    test_values: (value: ValuesFloat) -> ValuesFloat,
}

struct Point {
    x: int,
    y: int,
}

type Types {
    IntType: int,
    StringType: string,
}

-- Strings
const Names {
    name: "Adriano",
    surname: "Souza",
}

-- floats
const ValuesFloat {
    pi: 3.14,
    sqrt: 2.55,
    onedw: 122332.0,
}

-- integers
const ValuesInteger {
    one: 1,
    two: 2,
    three: 3,
}

-- uuids
const ValuesUuid {
    first: dee75f77-c47d-4181-bef0-6ac98d3e5a33,
    second: c45663f3-f68f-4c6b-b35d-c5f0206105cd,
    third: dbb39e64-6850-4161-8338-c9c66d792279,
    fourth: 2daa47b4-52cb-41af-970e-3cad8fc5f2ad,
}