name: idl_dart
version: 1.0.0

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  meta: ^1.3.0-nullsafety.6
  dart_style: ^1.3.10
  code_builder: ^3.5.0
  build: ^1.6.1
  built_collection: ^5.0.0-nullsafety.0 
  ffi: ^0.2.0-nullsafety.1
  json_annotation: ^4.0.0-nullsafety.0 
  yaml: ^3.0.0-nullsafety.0
  pub_semver: ^1.4.4-nullsafety.0
  tuple: 2.0.0-nullsafety.0


dev_dependencies:
  test: ^1.16.0-nullsafety.13
  build_runner: ^1.11.0
  json_serializable: ^4.0.0-nullsafety.0 
  pedantic: ^1.10.0-nullsafety.3